site_name: nanosamfw Project Documentation
site_description: Documentation for the nanosamfw project
site_url: "https://nanosamfw.github.io/nanosamfw/"
repo_url: "https://github.com/yanuino/nanosamfw"
repo_name: "yanuino/nanosamfw"
edit_uri: "edit/main/docs/"

strict: true
use_directory_urls: true

theme:
  name: material
  logo: assets/images/128.png
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.magiclink


plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            separate_signature: true
            members_order: source
            inherited_members: true
            filters: ["!^_"]
            heading_level: 2
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Paris
      locale: en
      fallback_to_build_date: true

nav:
  - Index: index.md
  - Core API:
    - FUS Client: api/fus.client.md
    - Cryptography: api/fus.crypto.md
    - Device ID: api/fus.deviceid.md
    - Firmware: api/fus.firmware.md
    - Errors: api/fus.errors.md
  - Download API:
    - Service: api/download.service.md
    - Firmware Repository: api/download.firmware_repository.md
    - Configuration: api/download.config.md
  - Device Detection:
    - Overview: api/device.md
    - Detector: api/device.detector.md
    - Reader: api/device.reader.md
    - Models: api/device.models.md
    - Errors: api/device.errors.md
  - Database:
    - Schema: database/schema.md
    - IMEI Repository: api/download.imei_repository.md


extra:
  release_tag: !ENV [RELEASE_TAG, '']
  release_title: !ENV [RELEASE_TITLE, '']
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanuino/nanosamfw
      name: GitHub
  generator: false
