[gui]
btn_dryrun = false  # If true, the GUI will show the "Dry run" checkbox.
btn_autofus = false  # If true, the GUI will show the "Auto FUS Mode" checkbox.

[devices]
auto_fusmode = false # If true, the application will automatically enter the device into FUS mode when needed.
csc_filter = ""    # Comma-separated list of CSC codes to filter devices. Leave empty ("") to disable filtering.

[firmware]
unzip_home_csc = false  # If false, the application will not unzip the Home CSC file when extracting firmware packages.